### ISSUE TITLE
inode capacity filling up

### ISSUE THREAD

**Issue by amuessig** [bosh-prometheus/prometheus-boshrelease#210]
Summary
======

The inodes of persistent disk running full.

Description
========

I have prometheus and grafana deployed on a single vm.
One week ago, it started sending out mail alerts (`alertname = BOSHJobPersistentDiskInodesExhausted`) at the weekend until the persistent disk was full - then scrapeerrors occured. Afterwards I increased the persistent disk and recreated the vm. It worked for like 5 days, then the same procedure came up again: Firstly I received `BOSHJobPersistentDiskInodesExhausted` alerts. Then scrape errors and the Grafana UI cannot be accessed. Afterwards, when the disk was full, Scrape errors of bosh-exporter occured.
I only have a reasonable amount of deployments (<10 deployments).

Troubleshooting
===========
I checked `bosh vms --vitals` and saw that inodes are running out of disk:
```
$ bosh vms --vitals

Instance                                           Persistent Disk Usage

prometheus/some-id          31% (100i%)
```
(To verify, I also issued `df -i /var/vcap/store` on the vm.)

I had a look on the vm to see the most recently created files by issuing `find -cmin 2880`:
```
$ cd /var/vcap/store
$ find -cmin 2880
./prometheus/48/*.db
./prometheus/49/*.db
./prometheus/14/*.db
./prometheus/4a/*.db
./prometheus/4b/*.db
```
In the aformentioned folders, a lot of database files were created.

I did some further troubleshooting and found that prometheus is issueing this huge amount of files:
```
$ bosh ssh prometheus
prometheus/<some-id>:/var/vcap/store# du -s * | sort -nr | head -3
28747480        prometheus
1930056 influxdb
1512    grafana
prometheus/<some-id>:/var/vcap/store# find prometheus/ -type f | wc -l
6405186
prometheus/<some-id>:/var/vcap/store# find influxdb/ -type f | wc -l
215
```

Deployment Details
=============
* Infrastructure: vsphere
* Stemcell ubuntu-trusty: version 3468.42
* Prometheus: version 21.1.1
* influxdb: version 7
* node-exporter: version 3.0.1
* os-conf: version 13
* syslog: version 11

For monitoring concourse, influxdb is used and retention is `properties.influxdb.retention = "90d"`.

My Prometheus job configuration:

```
instance_groups:
  jobs:
  - name: prometheus
    release: prometheus
    properties:
      prometheus:
        rule_files:
          - /var/vcap/jobs/bosh_alerts/bosh_jobs.alerts
          - /var/vcap/jobs/bosh_alerts/bosh_processes.alerts
          - /var/vcap/jobs/bosh_alerts/bosh_system.alerts
          - /var/vcap/jobs/bosh_alerts/prometheus_bosh_exporter.alerts
          - /var/vcap/jobs/probe_alerts/probe.alerts
          - /var/vcap/jobs/prometheus_alerts/prometheus.alerts
        global:
          scrape_interval: 1m
          scrape_timeout: 1m
        scrape_configs:
          - job_name: bosh-mgmt
            static_configs:
              - targets:
                - localhost:9190
          - job_name: prometheus
            static_configs:
              - targets:
                - localhost:9090
          - job_name: node
            file_sd_configs:
              - files:
                - /var/vcap/store/bosh_exporter/bosh_target_groups.json
            relabel_configs:
              - source_labels: [__meta_bosh_job_process_name]
                regex: node_exporter
                action: keep
              - source_labels: [__address__]
                regex: "(.*)"
                target_label: __address__
                replacement: "${1}:9100"
```

So, is this behaviour expected to get flooded by that many `*.db` files?
I am quite unsure what is the root cause of the issue and how to fix it..

**Comment by mkuratczyk** [comment]
Hi Alex!

Prometheus v1 is indeed inode-hungry. The easiest way to resolve this is to give Prometheus a larger persistent disk because BOSH calculates the number of inodes based on the disk size so larger disk => more inodes. I haven't checked that but as far as I understand Prometheus v2 storage redesign, upgrading to v2 should resolve this issue for you completely.

**Comment by amuessig** [comment]
Hi @mkuratczyk - thanks for the reply.
I tried upgrading to the most recent prometheus release (v22.1.1) and said that I do not care about old data. So, I didn't do any migration.
How do I get rid of all the old data since the inode usage is still 100i% after upgrading.. Is there any command to enforce cleanup?

**Comment by mkuratczyk** [comment]
I haven't played with v22 much but I'm surprised this is even possible - v22 defines a new instance group (`prometheus2`) so it should get a completely new persistent disk. No idea how you could have the same disk reattached. You can set your retention period to prevent filling the disk I guess.

**Comment by frodenas** [comment]
@amuessig Does the inode problem still persists after upgrading the prometheus release version?

**Comment by amuessig** [comment]
It seems to be fixed since upgrading.

**Comment by dohq** [comment]
same probrem,
I used version *prometheus     23.1.0*   5a58990*

```
grafana/f640e3f5-9689-4f35-bc11-993acecf63eb:~# df -i /dev/xvdf1
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/xvdf1      65280 63063  2217   97% /var/vcap/store
grafana/f640e3f5-9689-4f35-bc11-993acecf63eb:~#
grafana/f640e3f5-9689-4f35-bc11-993acecf63eb:~# df -hP /dev/xvdf1
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf1      988M  253M  669M  28% /var/vcap/store
grafana/f640e3f5-9689-4f35-bc11-993acecf63eb:~#
```
